# preload = /home/remy/heavydata/wallpapers/catalina/Catalina-1.jpg
# preload = /home/remy/heavydata/wallpapers/catalina/Catalina-2.jpg
# preload = /home/remy/heavydata/wallpapers/catalina/Catalina-3.jpg
# preload = /home/remy/heavydata/wallpapers/catalina/Catalina-4.jpg
# preload = /home/remy/heavydata/wallpapers/catalina/Catalina-5.jpg
# preload = /home/remy/heavydata/wallpapers/catalina/Catalina-6.jpg
# preload = /home/remy/heavydata/wallpapers/catalina/Catalina-7.jpg
# preload = /home/remy/heavydata/wallpapers/catalina/Catalina-8.jpg

# wallpaper = eDP-1,/home/remy/heavydata/wallpapers/catalina/Catalina-4.jpg

preload = /home/remy/hdata/wallpapers/artemis/art002e009279.jpg
preload = /home/remy/hdata/wallpapers/artemis/art002e009283.jpg
preload = /home/remy/hdata/wallpapers/artemis/art002e009288.jpg
preload = /home/remy/hdata/wallpapers/artemis/art002e009301.jpg
preload = /home/remy/hdata/wallpapers/artemis/art002e009567.jpg
preload = /home/remy/hdata/wallpapers/artemis/art002e009571.jpg
preload = /home/remy/hdata/wallpapers/artemis/moon_and_earth.jpg
preload = /home/remy/hdata/wallpapers/artemis/NHQ20260401_admin_0021.jpg
preload = /home/remy/hdata/wallpapers/artemis/NHQ202604010238.jpg

wallpaper = eDP-1,/home/remy/hdata/wallpapers/artemis/art002e009279.jpg

ipc = off

