hl.on("hyprland.start", function()
    hl.exec_cmd("hypridle")
    hl.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ 0")
    hl.exec_cmd("wpaperd -d")
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("mako")
    hl.exec_cmd("waybar")
end)
